name = "lunavoe-rsvp"
main = "worker/index.js" 

account_id = "df47902d7c828a919a05556fe973ff2f"
workers_dev = true

compatibility_date = "2025-12-01"

[[kv_namespaces]]
binding = "RSVP_GLORIAJM"
id = "2db44c4c8aaa4923b0890f4cc092119c"
